name: Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: NgrokPre
      run: if grep pre .github/ngrok ; then bash .github/debug-github-actions.sh ; fi
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        DOCKER_USER: ${{secrets.DOCKER_USER}}        
    - name: WaitPre
      run: if grep pre .github/ngrok ; then bash .github/wait.sh ; fi
   
    - name: Build
      shell: bash
      env: 
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: |
        bash setup.sh
        source source-me-first
        make
        make push

    - name: NgrokPost
      run: if grep post .github/ngrok ; then bash .github/debug-github-actions.sh ; fi
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
        DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: WaitPost
      run: if grep post .github/ngrok ; then bash .github/wait.sh ; fi
      
